name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - manylinux2014_x86_64
        python-version:
          - cp35-cp35m
    container: quay.io/pypa/${{ matrix.container }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Print submodule commits
      run: git submodule status > submodule.txt
    - name: Install system dependencies
      run: yum install -y fontconfig-devel mesa-libGL-devel xorg-x11-server-Xvfb mesa-dri-drivers
    - uses: actions/cache@v1
      id: cache
      with:
        path: skia/out/Release
        key: ${{ matrix.container }}-skia-out-${{ hashFiles('submodule.txt') }}
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Build gn
      env:
        CC: gcc
        CXX: g++
        AR: ar
        LDFLAGS: -lrt
      run: |
        git clone https://gn.googlesource.com/gn
        cd gn
        python build/gen.py
        ninja -C out gn
        cd ..
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        cp -f ../gn/out/gn bin/gn  # Replace gn.
        bin/gn gen out/Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false extra_cflags_cc=["-frtti"] extra_ldflags=["-lrt"]'
        ninja -C out/Release skia skia.h
        rm -rf out/Release/obj
        cd ..
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Set up Python
      run: echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
    - name: Build python binding
      run: |
        python -m pip install -U pip
        python -m pip install pybind11 numpy
        python setup.py install
    - name: Test
      run: |
        python -m pip install pytest glfw
        xvfb-run -s "-screen 0 640x480x24" python -m pytest tests
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Print submodule commits
      run: git submodule status > submodule.txt
    - uses: actions/cache@v1
      id: cache
      with:
        path: skia/out/Release
        key: ${{ runner.os }}-skia-out-${{ hashFiles('submodule.txt') }}
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Set PATH
      run: echo "::add-path::$PWD/depot_tools"
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Build Skia
      run: |
        cd skia
        python tools/git-sync-deps
        bin/gn gen out/Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false extra_cflags_cc=["-frtti"]'
        ninja -C out/Release skia skia.h
        rm -rf out/Release/obj
        cd ..
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build python binding
      env:
        CC: clang
        CXX: clang++
      run: |
        python -m pip install -U pip
        python -m pip install pybind11 numpy
        python setup.py install
    - name: Test
      run: |
        python -m pip install pytest pyopengl pyopengl-accelerate
        python -m pytest tests
    - name: Build docs
      run: |
        python -m pip install sphinx
        make -C docs html
    - name: Deploy docs to gh-pages
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ x86, x64 ]
        python-version: [3.5]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Print submodule commits
      run: git submodule status > submodule.txt
    - uses: actions/cache@v1
      id: cache
      with:
        path: skia\out\Release
        key: ${{ runner.os }}-${{ matrix.arch }}-skia-out-${{ hashFiles('submodule.txt') }}
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Set PATH
      run: echo "::add-path::$PWD\depot_tools"
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Build Skia
      run: |
        cd skia
        python tools\git-sync-deps
        bin\gn gen out\Release --args='is_official_build=true skia_enable_tools=true skia_use_system_libjpeg_turbo=false skia_use_system_libwebp=false skia_use_system_libpng=false skia_use_system_icu=false skia_use_system_harfbuzz=false skia_use_system_expat=false skia_use_system_zlib=false extra_cflags_cc=[\"/GR\", \"/EHsc\"] target_cpu=\"${{ matrix.arch }}\"'
        ninja -C out\Release skia skia.h
        rm out\Release\obj -r -fo
        cd ..
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
    - name: Build python binding
      env:
        DISTUTILS_USE_SDK: 1
      run: |
        $path = vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
        $args = '-arch=${{ matrix.arch }}'
        if ($path) {
            $path = join-path $path 'Common7\Tools\vsdevcmd.bat'
            if (test-path $path) {
                cmd /s /c """$path"" $args && set" | where { $_ -match '(\w+)=(.*)' } | foreach {
                    $null = new-item -force -path "Env:\$($Matches[1])" -value $Matches[2]
                }
            }
        }
        python -m pip install -U pip
        python -m pip install pybind11 numpy
        python setup.py install
    - name: Test
      run: |
        python -m pip install pytest glfw
        python -m pytest tests
